version: '3'
services:
  node:
    environment:
      - NG_CLI_ANALYTICS=false
    build: .
    ports:
      - "4200:4200"
      - "9876:9876"
    volumes:
      - "./dqx_blacksmith:/projects"
    tty: true
    command: /bin/bash -c "ng serve --host 0.0.0.0"
